server:
    port: 9000

spring:
    application:
        name: gateway
    cloud:
        gateway:
            routes:
            - id: api
              uri: http://localhost:8081
              predicates:
              - Path=/user/**
